In [ ]:
import pandas as pd

df = pd.read_csv('/content/FOOD List.csv')
df.head()

,Order_ID,Customer_ID,Customer Name,Food Name,city,Total Orders,Total Spending,Rating
0,101,C001,Arun Kumar,Pizza,Chennai,15,4500,4.8
1,102,C002,Priya Sharma,Burger,Bangalore,12,3800,4.6
2,103,C003,Rahul Singh,Sandwich,Hyderabed,20,6200,4.9
3,104,C004,Karthik Raj,Dose,Mumbai,10,2900,4.5
4,105,C005,Divay,Idli,Coimbatore,18,5400,4.7

In [ ]:
total_orders = len(df)
print("Total Orders:", total_orders)

Total Orders: 20

In [ ]:
popular_dishes = df['Food Name'].value_counts()

print(popular_dishes.head(10))

Food Name
Pizza         1
Burger        1
Sandwich      1
Dose          1
Idli          1
Pongal        1
Fried Rice    1
Noodles       1
Biryani       1
Parotta       1
Name: count, dtype: int64

In [ ]:
city_orders = df['city'].value_counts()

print(city_orders)

city
Chennai       2
Bangalore     2
Hyderabed     2
Mumbai        2
Coimbatore    2
Kochi         2
Delhi         2
Vijayawada    2
Madurai       2
Pune          2
Name: count, dtype: int64

In [ ]:
total_spending = df['Total Spending '].sum()

print("Total Spending:", total_spending)

Total Spending: 78000

In [ ]:
avg_rating = df['Rating'].mean()

print("Average Rating:", round(avg_rating, 2))

Average Rating: 4.61

In [ ]:
print("Total Customers:", df['Customer_ID'].nunique())
print("Top Food:", df['Food Name'].mode()[0])
print("Top City:", df['city'].mode()[0])
print("Total Spending:", df['Total Spending '].sum())
print("Average Rating:", round(df['Rating'].mean(), 2))

Total Customers: 20
Top Food: Biryani
Top City: Bangalore
Total Spending: 78000
Average Rating: 4.61

In [ ]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['Order_ID', 'Customer_ID', 'Customer Name', 'Food Name', 'city',
       'Total Orders', 'Total Spending', 'Rating'],
      dtype='object')

In [ ]:
df['Total Spending']

0     4500
1     3800
2     6200
3     2900
4     5400
5     2300
6     4100
7     3200
8     4800
9     2700
10    6200
11    4800
12    3200
13    4500
14    2300
15    2300
16    4100
17    3200
18    4800
19    2700
Name: Total Spending, dtype: int64